#@TYPE: MACHINE
#@NAME: SRG-iMX8P-A11-04
#@DESCRIPTION: SRG-iMX8P-A11-04 Machine Configuration
#@SOC: i.MX8P

require conf/machine/include/srg-imx8p-a11-common.inc

MACHINE_BASE = "srg-imx8p-a11"

WKS_FILE:srg-imx8p-a11-04 = "aaeon-nxp-imx8-welma.wks.in"

# Supported boot devices: emmc, sdcard.
# Only one value should be selected in BOOT_DEVICE variable.
BOOT_DEVICE ??= "sdcard"
BOOT_DEVICE[emmc] = "/dev/mmcblk2"
BOOT_DEVICE[sdcard] = "/dev/mmcblk1"
# Path of selected boot device
BOOT_DEV_PATH = "${@ d.getVarFlag('BOOT_DEVICE', d.getVar('BOOT_DEVICE'))}"
# Bootflags on select boot device
BOOTFLAGS_PATH ?= "${BOOT_DEV_PATH}"
BOOT_DEV_PART_PREFIX = "p"
FIRST_ACTIVE_PARTITION_INDEX = "1"

UBOOT_DTB_LOADADDRESS = "0x50480000"
UBOOT_RD_LOADADDRESS = "0x60000000"